
/*
  # GradTrack - Graduate Tracking System Schema

  ## Overview
  Creates the core `graduates` table that stores complete graduate journey data
  from primary school through employment, including funding and mobility tracking.

  ## New Tables

  ### graduates
  Central table capturing every graduate's full academic and professional journey:
  - **Identity**: id (uuid pk), graduate_id (auto-generated code), name, email, phone, DOB, gender
  - **Primary Education**: primary_school name
  - **Secondary Education**: O-Level school name and A-Level school name
  - **University**: institution, program, degree level, start/end years, completion status, location
  - **Funding**: type (scholarship/loan/self_funded/government_grant/mixed), sponsor, loan amount, repayment status
  - **Employment**: status, employer, role, sector, work location, country of residence, employment date
  - **Derived**: graduation_year for time-to-employment calculations

  ## Security
  - RLS enabled on graduates table
  - Public read/write policies for anonymous users (no auth required for this system)

  ## Notes
  1. graduate_id is a human-readable code (e.g., GRD-2024-001) generated by the application
  2. loan_amount and repayment_status only apply when funding_type is 'loan' or 'mixed'
  3. employment_date + graduation_year enables time-to-employment analytics
  4. study_location distinguishes local vs abroad for mobility analytics
*/

CREATE TABLE IF NOT EXISTS graduates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  graduate_id text UNIQUE NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text DEFAULT '',
  phone text DEFAULT '',
  date_of_birth date,
  gender text DEFAULT 'not_specified',

  -- Primary Education
  primary_school text DEFAULT '',

  -- Secondary Education
  secondary_o_level_school text DEFAULT '',
  secondary_a_level_school text DEFAULT '',

  -- University Education
  university_institution text DEFAULT '',
  university_program text DEFAULT '',
  degree_level text DEFAULT 'bachelor',
  university_start_year int,
  university_end_year int,
  completion_status text DEFAULT 'completed',
  study_location text DEFAULT 'local',
  study_country text DEFAULT '',

  -- Funding
  funding_type text DEFAULT 'self_funded',
  sponsor_name text DEFAULT '',
  loan_amount numeric(12,2) DEFAULT 0,
  repayment_status text DEFAULT 'not_applicable',

  -- Employment
  employment_status text DEFAULT 'unemployed',
  employer text DEFAULT '',
  job_role text DEFAULT '',
  sector text DEFAULT '',
  work_location text DEFAULT 'local',
  further_study_location text DEFAULT 'local',
  further_study_country text DEFAULT '',
  further_study_field text DEFAULT '',
  further_study_graduation_year int,
  further_study_funding text DEFAULT 'self_funded',
  country_of_residence text DEFAULT '',
  employment_date date,
  graduation_year int,

  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_graduates_program ON graduates(university_program);
CREATE INDEX IF NOT EXISTS idx_graduates_employment_status ON graduates(employment_status);
CREATE INDEX IF NOT EXISTS idx_graduates_funding_type ON graduates(funding_type);
CREATE INDEX IF NOT EXISTS idx_graduates_completion_status ON graduates(completion_status);

ALTER TABLE graduates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view graduates"
  ON graduates FOR SELECT
  TO anon, authenticated
  USING (auth.role() = 'anon' OR auth.role() = 'authenticated');

CREATE POLICY "Public can insert graduates"
  ON graduates FOR INSERT
  TO anon, authenticated
  WITH CHECK (auth.role() = 'anon' OR auth.role() = 'authenticated');

CREATE POLICY "Public can update graduates"
  ON graduates FOR UPDATE
  TO anon, authenticated
  USING (auth.role() = 'anon' OR auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'anon' OR auth.role() = 'authenticated');

CREATE POLICY "Public can delete graduates"
  ON graduates FOR DELETE
  TO anon, authenticated
  USING (auth.role() = 'anon' OR auth.role() = 'authenticated');
